# Generated by Django 3.0.4 on 2020-03-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ext', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='nmae',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='register',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
