# Generated by Django 3.0.4 on 2020-04-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ext', '0002_auto_20200330_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='kkkkkkkkkkk', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default='kkkkkkkkk', max_length=30),
            preserve_default=False,
        ),
    ]
