# Generated by Django 3.0.4 on 2020-04-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ext', '0004_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Profile',
        ),
    ]
