# Generated by Django 3.0.4 on 2020-04-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ext', '0005_auto_20200412_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
